name: Odoo CI/CD - Like Odoo.sh

on:
  push:
    branches: [main, staging]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Run Odoo Tests with official image
        run: |
          docker run --rm \
            -e DB_HOST=host.docker.internal \
            -e DB_PORT=5432 \
            -e DB_USER=odoo \
            -e DB_PASSWORD=odoo \
            odoo:16.0 \
            odoo --db_host=host.docker.internal --db_user=odoo --db_password=odoo \
              --test-enable --stop-after-init --addons-path=/mnt/odoo/addons,/mnt/custom_addons

