name: Odoo CI/CD - Like Odoo.sh

on:
  push:
    branches: [main, staging]
  pull_request:

jobs:
  test:
    name: 🧪 Test Odoo Addons
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t odoo-test -f Dockerfile .

      - name: Run Odoo Tests in Container
        run: |
          docker run --rm \
            -e DB_HOST=host.docker.internal \
            -e DB_PORT=5432 \
            -e DB_USER=odoo \
            -e DB_PASSWORD=odoo \
            odoo-test \
            odoo-bin -d test_db \
              --db_host=host.docker.internal \
              --db_user=odoo \
              --db_password=odoo \
              --test-enable \
              --stop-after-init \
              --addons-path=/mnt/odoo/addons,/mnt/custom_addons

      - name: Upload Logs on Failure
        if: failure()
        run: echo "❌ Tests failed. See logs above like in Odoo.sh."
