name: Odoo CI/CD - Like Odoo.sh

on:
  push:
    branches: [main, staging]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U odoo"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for PostgreSQL to be healthy
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -p 5432 -U odoo; then
              echo "Postgres is ready!"
              break
            fi
            echo "Waiting for postgres..."
            sleep 5
          done

      - name: Detect GitHub Docker network
        id: detect-network
        run: |
          NETWORK_NAME=$(docker network ls --filter name=github --format "{{.Name}}" | head -n 1)
          echo "network=$NETWORK_NAME" >> $GITHUB_OUTPUT

      - name: Run Odoo tests in Docker
        run: |
          docker run --rm \
            --network=${{ steps.detect-network.outputs.network }} \
            -v ${{ github.workspace }}/custom_addons:/mnt/custom_addons \
            odoo:16.0 \
            odoo --db_host=postgres \
                 --db_port=5432 \
                 --db_user=odoo \
                 --db_password=odoo \
                 --test-enable --stop-after-init \

